In [4]:
from mxnet import nd

In [6]:
x=nd.arange(12)
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [7]:
x.shape()

TypeError: 'tuple' object is not callable

In [8]:
x.shape

(12,)

In [9]:
x.size

12

In [10]:
X = x.reshape((3,4))

In [11]:
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>